---
name: Build Kernel Package

# yamllint disable-line rule:truthy
on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'

      - name: 'Checkout Repo'
        uses: actions/checkout@v2

      - name: Build script
        id: build
        run: |
          VERSION=$(grep ^KERNEL_VERSION build.sh | head -n1| cut -d = -f2)
          REL=$(grep "PKGREL=\d*" build.sh | cut -d = -f2)
          #REL=$( git tag |grep -F $VERSION|sort -r|head -n1|tr -d v)
          echo Building $VERSION-$REL
          echo "::set-output name=tag::${VERSION}-${REL}"

          DOCKER_IMAGE=debian:unstable
          docker pull ${DOCKER_IMAGE}
          docker run -t -v "$(pwd):/repo" ${DOCKER_IMAGE} /bin/bash -c 'cd /repo && ./build.sh'
          echo Contents of '$(pwd)/packages'
          ls -l $(pwd)/packages

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-T2-${{ steps.build.outputs.tag }}
          path: |
            packages/Packages.gz
            packages/sha256
            packages/*.deb
            packages/kernel_config*

      - name: Release
        if: github.ref == 'refs/heads/Mainline'
        uses: softprops/action-gh-release@v1
        with:
          files: |
             packages/Packages.gz
             packages/sha256
             packages/*.deb
             packages/kernel_config*
          tag_name: v${{ steps.build.outputs.tag }}
          body_path: ${{ github.workspace }}/.github/workflows/instructions.txt
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
